### ISSUE TITLE
Could we support IOS?

### ISSUE THREAD

**Issue by storytellerF** [ethauvin/urlencoder#11]

**Comment by ethauvin** [comment]
@storytellerF I've just released a [couple artifacts](https://central.sonatype.com/search?namespace=net.thauvin.erik.urlencoder) for iOS. But I don't have a way to test them right now. Let me know if they work for you.

**Comment by storytellerF** [comment]
But it could not use at commonMain.
> Could not find net.thauvin.erik.urlencoder:urlencoder-lib-iossimulatorarm64:1.4.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/net/thauvin/erik/urlencoder/urlencoder-lib-iossimulatorarm64/1.4.0/urlencoder-lib-iossimulatorarm64-1.4.0.pom
    - https://dl.google.com/dl/android/maven2/net/thauvin/erik/urlencoder/urlencoder-lib-iossimulatorarm64/1.4.0/urlencoder-lib-iossimulatorarm64-1.4.0.pom
    - https://maven.pkg.jetbrains.space/public/p/compose/dev/net/thauvin/erik/urlencoder/urlencoder-lib-iossimulatorarm64/1.4.0/urlencoder-lib-iossimulatorarm64-1.4.0.pom
  Required by:
      project :shared > net.thauvin.erik.urlencoder:urlencoder-lib:1.4.0

and my target
```kotlin
listOf(
    iosX64(),
    iosArm64(),
    iosSimulatorArm64()
).forEach { iosTarget ->
    iosTarget.binaries.framework {
        baseName = "shared"
        isStatic = true
    }
}
```

**Comment by ethauvin** [comment]
@storytellerF I just added the [iOS simulator artifact](https://central.sonatype.com/search?namespace=net.thauvin.erik.urlencoder) that you were trying to use. Give it another try and let me know if it works for you.

**Comment by storytellerF** [comment]
Problem solved!
