### ISSUE TITLE
Function 'encode' can not be called with Kotlin 2.0.0-Beta

### ISSUE THREAD

**Issue by mgroth0** [ethauvin/urlencoder#12]
When I try to call `UrlEncoderUtil.encode` from a `macOsArm64` test I get an error.

Kotlin version 2.0.0-Beta4
Library version 1.4.0

<details><summary>Stack Trace</summary>
<p>

```
Function 'encode' can not be called: No function found for symbol 'net.thauvin.erik.urlencoder/UrlEncoderUtil.encode|encode#static(kotlin.String;kotlin.String;kotlin.Boolean){}[0]'
i: <missing declarations>: No function found for symbol 'net.thauvin.erik.urlencoder/UrlEncoderUtil.encode|encode#static(kotlin.String;kotlin.String;kotlin.Boolean){}[0]'


kotlin.native.internal.IrLinkageError: Function 'encode' can not be called: No function found for symbol 'net.thauvin.erik.urlencoder/UrlEncoderUtil.encode|encode#static(kotlin.String;kotlin.String;kotlin.Boolean){}[0]'
        at kotlin.Throwable#<init>(/opt/buildAgent/work/4b543f97c4b0507f/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:28)
        at kotlin.Error#<init>(/opt/buildAgent/work/4b543f97c4b0507f/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:12)
        at kotlin.native.internal.IrLinkageError#<init>(/opt/buildAgent/work/4b543f97c4b0507f/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/RuntimeUtils.kt:137)
        at kotlin.native.internal#ThrowIrLinkageError(/opt/buildAgent/work/4b543f97c4b0507f/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/RuntimeUtils.kt:141)
```

</p>
</details>

**Comment by ethauvin** [comment]
@mgroth0 Thanks for the report.

Does it work for you with Kotlin 1.9.22? If not, what dependency are you using?

**Comment by ethauvin** [comment]
> Maybe it is more accurate to say that removing @JvmStatic is a workaround, not a fix. The actual bug is probably something with the beta K2 version I am using, I would guess.

Very likely. See my comments on #13

**Comment by aSemy** [comment]
I see some various issues on YouTrack regarding 'IrLinkageError' .

https://youtrack.jetbrains.com/issues?q=IrLinkageError

Maybe something else is the cause, and `@JvmStatic` is the first symptom? Can you look at any of the issues @mgroth0 and see if your project has a similar set up?

Removing `@JvmStatic` might cause issues with Java interop. There should probably be a Java test to verify if `@JvmStatic` is necessary - I don't think there is one at the moment?

**Comment by ethauvin** [comment]
> Removing `@JvmStatic` might cause issues with Java interop. There should probably be a Java test to verify if `@JvmStatic` is necessary - I don't think there is one at the moment?

It does break Java interop. There's currently no test for it, but I tried it.

**Comment by Flyfish233** [comment]
Same problem and it happening on other libraries contain `@JvmStatic` object. This is more likely a compiler issue and I'm waiting for fixes from JetBrains.

**Comment by ethauvin** [comment]
@Flyfish233 Thanks for letting us know.

**Comment by aSemy** [comment]
Please make an issue on YouTrack https://kotl.in/issue
